### ISSUE TITLE
Camunda Modeler v4.9 breaks plugin

### ISSUE THREAD

**Issue by phehr2** [richig-vienna/camunda-modeler-bpmn-js-plugin-spectrum-color-picker#1]
Camunda Modeler v4.9 now includes support for the BPMN in Color spec. This plugin does not work with this new version of the Modeler. Exceptions are encountered, preventing shapes from receiving the selected colors.

**Comment by richig-vienna** [comment]
The error should have occurred only when using the "auto-mode", where the color value was not passed with a leading "#" character.

The fix was tested with version 4.2.0 and 4.9.0.
